const withErrorCatcher = (handler) => async (req, res, next) => {
  try {
    await handler(req, res, next);
  } catch (err) {
    next(err);
  }
};

module.exports = withErrorCatcher;
